sudo: false
language: python
python:
  - 2.7
  - 3.5

install:
  - pip install --user django mezzanine
  - pip install --user tox tox-travis
  - pip install --user coverage coveralls

script:
  - tox -r
